[package]
name = "adventofcode"
version = "0.1.0"
authors = ["Nathan Jent <nathanjent@gmail.com>"]

[dependencies]
md5 = "0.2.1"
regex = "0.2.1"
simple_json = "0.2.3"
abc = "0.2.3"
rand = "0.3.15"
num = "0.1.36"
generic-matrix = "0.0.7"
